### ISSUE TITLE
Says it's loading, goes back to wii menu.

### ISSUE THREAD

**Issue by James10898** [dborth/vba-wii#338]
So I have the channel and a 2gb sd (no hc), in my \vbagx\ folder I have the folders: \roms, \save, and \cheat. I have 3 roms in the roms folder and nothing else.
So here's the Important thing: whenever I try to load vbagx channel, It just says "loading" then goes back to the wii menu.

**Comment by carstene1ns** [comment]
Stupid question, but did you install vba's actual `boot.dol` as well?

**Comment by dborth** [comment]
You need the boot.dol. It's not optional. All the channel does is launch the boot.dol.
