### ISSUE TITLE
Unable to Build boot.dol

### ISSUE THREAD

**Issue by JeffReeves** [dborth/vba-wii#340]
No where in this Git repo am I able to find out how to build the actual boot.dol file for use in the apps directory on my SD card. I've tried checked through earlier commits and cannot find the supposed "vbagx" directory. Please update your readme file and file list to make this easier to use. Thank you!

**Comment by dborth** [comment]
Download from the releases page: https://github.com/dborth/vba-wii/releases

Go on a forum eg: gbatemp.net if you need further help.
