### ISSUE TITLE
How do I install this? There is no apps folder like the readme.txt says

### ISSUE THREAD

**Issue by Nawor3565** [dborth/vba-wii#341]
Im new to this whole soft-modding thing, so Im not really sure what Im doing wrong.The readme.txt says to extract the .zip to the SD card, and you'll see an Apps folder and a vbagx folder. I see nether in the zip. Just a "hbc" folder, a "source" folder, and a bunch of other files. Should I just copy them over anyway, and see if it appears in the HBC? To the best of my knowledge, things only appear in the HBC if they are in the apps folder. Do I use another program to compile them or something? Any help?

**Comment by GB-CG** [comment]
Did you check this? https://github.com/dborth/vba-wii/releases/download/2.2.8/Visual.Boy.Advance.GX.2.2.8.zip

**Comment by Nawor3565** [comment]
Ohhhhh..... I think I might see what the issue is. I was downloading the "Master" version of these, which Im guessing is for developers. Sorry about that!
